const API=location.origin;
let key=localStorage.getItem("4ndev_api_key")||"",me=null,currentProject=null,currentFiles=[],lastBuilderPlan=null;
const $=s=>document.querySelector(s);
const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
async function api(path,opt={}){const headers={"Content-Type":"application/json",...(opt.headers||{})};if(key)headers.Authorization="Bearer "+key;const r=await fetch(API+path,{...opt,headers});let d={};try{d=await r.json()}catch{}if(!r.ok)throw new Error(d.error||("HTTP "+r.status));return d}
function showOnboarding(msg=""){$("#consoleScreen").classList.add("hidden");$("#onboardingScreen").classList.remove("hidden");if(msg){$("#createKeyError").textContent=msg;$("#createKeyError").classList.remove("hidden")}}
async function refreshMe(){me=(await api("/v1/me")).developer;$("#planBadge").textContent=(me.plan||"free").toUpperCase();$("#creditBadge").textContent=(me.credits??0)+" credits"}
function showConsole(){show("overview");refreshMe().catch(e=>{key="";localStorage.removeItem("4ndev_api_key");showOnboarding(e.message)})}
async function createDeveloperKey(){const b=$("#createKeyBtn"),name=$("#developerName").value.trim();$("#createKeyError").classList.add("hidden");if(!name){$("#createKeyError").textContent="Developer name is required.";$("#createKeyError").classList.remove("hidden");return}b.disabled=true;b.textContent="Creating API key…";try{const d=await fetch(API+"/v1/keys/create",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name})});let j={};try{j=await d.json()}catch{}if(!d.ok)throw new Error(j.error||("HTTP "+d.status));key=j.api_key;$("#createdApiKey").value=key;$("#createKeyStep").classList.add("hidden");$("#keyCreatedStep").classList.remove("hidden");sessionStorage.setItem("4ndev_new_api_key",key)}catch(e){$("#createKeyError").textContent=e.message;$("#createKeyError").classList.remove("hidden")}finally{b.disabled=false;b.textContent="Create API key"}}
async function copyCreatedKey(){const v=$("#createdApiKey").value;if(!v)return;try{await navigator.clipboard.writeText(v);$("#copyStatus").textContent="API key copied."}catch{$("#createdApiKey").select();document.execCommand("copy");$("#copyStatus").textContent="API key copied."}}
function continueToConsole(){localStorage.setItem("4ndev_api_key",key);sessionStorage.removeItem("4ndev_new_api_key");$("#onboardingScreen").classList.add("hidden");$("#consoleScreen").classList.remove("hidden");showConsole()}
function logoutDeveloper(){key="";localStorage.removeItem("4ndev_api_key");sessionStorage.removeItem("4ndev_new_api_key");showOnboarding()}
const pages={overview,models,playground,apiKeys,projects,usage,builder,docs,billing,settings};
function show(p){document.querySelectorAll(".nav").forEach(n=>n.classList.toggle("active",n.dataset.page===p));const v=pages[p]||overview;$("#main").innerHTML=v();bind(p);$("#sidebar").classList.remove("open")}
function title(t,s,actions=""){return '<div class="page-title"><div><h1>'+t+'</h1><p class="muted">'+s+'</p></div><div class="toolbar">'+actions+"</div></div>"}
function overview(){return title("Overview","Your 4N DEV developer workspace.")+'<div class="grid"><div class="card"><div class="label">Current plan</div><div class="metric">'+esc((me?.plan||"free").toUpperCase())+'</div></div><div class="card"><div class="label">Credits remaining</div><div class="metric">'+esc(me?.credits??"—")+'</div></div><div class="card"><div class="label">API access</div><div class="metric">Active</div></div><div class="card"><div class="label">Features</div><div class="metric">'+(me?.features?.length||0)+'</div></div></div><div class="section-head"><h2>Developer tools</h2></div><div class="grid3"><div class="card"><h3>Models</h3><p class="muted">Explore Chat, Coding, Image and Embeddings capabilities.</p><button class="ghost" data-go="models" type="button">View models →</button></div><div class="card"><h3>API Keys</h3><p class="muted">Authenticate your applications with 4N DEV Core.</p><button class="ghost" data-go="apiKeys" type="button">Manage keys →</button></div><div class="card"><h3>Usage</h3><p class="muted">Track requests and credits consumed by your API.</p><button class="ghost" data-go="usage" type="button">View usage →</button></div></div><div class="section-head"><h2>Quick start</h2></div><div class="card"><div class="code">Authorization: Bearer 4ndev_sk_…</div><div class="code" style="margin-top:10px">POST /v1/chat
{"input":"Hello 4N DEV"}</div></div>'}
function models(){const items=[["Chat","gpt-5.6-luna / 4n-dev-demo-chat","General purpose conversational AI. Demo mode falls back to 4n-dev-demo-chat.","/v1/chat","1 credit / request","POST"],["Coding","gpt-5.6-luna / 4n-dev-demo-coding","Code generation and programming assistance.","/v1/coding","5 credits / request","POST"],["Image","gpt-image-2 / 4n-dev-demo-image","AI image generation with low, medium and high quality.","/v1/image","10 / 25 / 50 credits","POST"],["Embeddings","text-embedding-3-small / 4n-dev-demo-embedding","Vector embeddings for search and retrieval.","/v1/embeddings","1 credit / request","POST"]];return title("Models","AI capabilities available through the 4N DEV API.")+'<div class="grid3">'+items.map(x=>'<div class="card model-card"><div class="model-name">'+x[0]+'</div><div class="model-id">'+x[1]+'</div><p class="muted">'+x[2]+'</p><span class="tag">'+x[3]+'</span><span class="tag">'+x[4]+'</span><div style="margin-top:15px"><button class="ghost use-model" data-model="'+x[0].toLowerCase()+'" type="button">Open in Playground →</button></div></div>').join("")+'</div>'}
function playground(){return title("Playground","Test 4N DEV models before integrating them into your application.")+'<div class="card stack"><div class="toolbar"><select id="playModel" style="max-width:260px"><option value="chat">Chat</option><option value="coding">Coding</option><option value="image">Image</option><option value="embeddings">Embeddings</option></select><span class="pill">Authenticated API request</span></div><textarea id="playInput" rows="8" placeholder="Write a prompt or coding request…"></textarea><button id="playRun" class="primary" type="button">Run</button><div id="playOutput" class="output">Output will appear here.</div></div>'}
function apiKeys(){const masked=key?key.slice(0,9)+"••••••••••••"+key.slice(-4):"—";return title("API Keys","Authenticate applications and keep secret keys out of client-side code.")+'<div class="card"><div class="section-head" style="margin-top:0"><h2>Connected key</h2><span class="pill ok">Active</span></div><div class="key-display">'+esc(masked)+'</div><p class="muted small">This console uses the connected key for Core API requests. The full secret is not rendered in the platform UI.</p><div class="toolbar"><button id="copyKey" class="ghost" type="button">Copy key</button><button id="forgetKey" class="danger" type="button">Remove from this device</button></div></div><div class="section-head"><h2>Authentication</h2></div><div class="card"><div class="endpoint">Authorization: Bearer 4ndev_sk_...</div><p class="muted">Use a server-side environment variable for production applications. Never expose a secret key in browser JavaScript.</p></div>'}
function projects(){return title("Projects","Organize files, builds and deployments by application.")+'<div class="card stack"><div class="toolbar"><input id="newProjectName" class="field" style="max-width:300px" placeholder="Project name"><button id="newProject" class="primary" type="button">Create project</button><button id="reloadProjects" class="ghost" type="button">Refresh</button></div><div id="projectList">Loading…</div></div><div id="projectWorkspace" class="hidden" style="margin-top:14px"></div>'}
function usage(){return title("Usage","API activity and credit consumption from the Core.")+'<div class="grid3"><div class="card"><div class="label">Credits remaining</div><div id="usageBalance" class="metric">—</div></div><div class="card"><div class="label">Total requests</div><div id="usageRequests" class="metric">—</div></div><div class="card"><div class="label">Records returned</div><div id="usageRecords" class="metric">—</div></div></div><div class="section-head"><h2>Recent activity</h2></div><div class="card"><div id="usageList">Loading…</div></div>'}
function builder(){return title("Builder","Plan, generate, review, build and deploy an application with the Core Builder.")+'<div class="card stack"><input id="projectName" class="field" placeholder="Project name (optional)"><textarea id="builderPrompt" rows="7" placeholder="Describe the application you want to build…"></textarea><div class="toolbar"><button id="planBtn" class="ghost" type="button">1. Prepare plan</button><button id="buildBtn" class="primary" type="button">2. Generate + Build + Deploy</button><span id="builderStatus" class="status"></span></div><div id="planOutput" class="output hidden"></div><div id="buildOutput" class="output">Builder output will appear here.</div></div>'}
function docs(){return title("Documentation","Reference for building with the 4N DEV Core API.")+'<div class="grid3"><div class="card"><h3>Quickstart</h3><p class="muted">Authenticate with a Bearer API key and make your first request.</p><div class="endpoint">POST /v1/chat</div></div><div class="card"><h3>Models</h3><p class="muted">Chat, Coding, Image and Embeddings endpoints are available according to plan features.</p></div><div class="card"><h3>Credits</h3><p class="muted">Requests consume 4N DEV credits. Usage responses include credits used and remaining.</p></div></div><div class="section-head"><h2>Example</h2></div><div class="card"><div class="code">curl https://fourn-dev-core.onrender.com/v1/chat \
  -H "Authorization: Bearer 4ndev_sk_..." \
  -H "Content-Type: application/json" \
  -d '{"input":"Hello"}'</div></div>'}
function billing(){return title("Billing","Plans, credits, orders and payments for your developer account.")+'<div class="grid3"><div class="card"><div class="label">Current plan</div><div class="metric">'+esc((me?.plan||"free").toUpperCase())+'</div></div><div class="card"><div class="label">Credits</div><div class="metric">'+esc(me?.credits??"—")+'</div></div><div class="card"><div class="label">Billing currency</div><div class="metric">MGA</div></div></div><div class="section-head"><h2>Plans</h2></div><div id="plans" class="three">Loading…</div><div class="section-head"><h2>Orders</h2></div><div class="card"><div id="orders">Loading…</div></div>'}
function settings(){return title("Settings","Developer account and local console settings.")+'<div class="two"><div class="card"><h3>Developer account</h3><div class="statline"><span>ID</span><strong>'+esc(me?.id||"—")+'</strong></div><div class="statline"><span>Name</span><strong>'+esc(me?.name||"—")+'</strong></div><div class="statline"><span>Plan</span><strong>'+esc(me?.plan||"—")+'</strong></div><div class="statline"><span>Credits</span><strong>'+esc(me?.credits??"—")+'</strong></div><div class="statline"><span>Scopes</span><strong>'+esc((me?.scopes||[]).join(", ")||"—")+'</strong></div></div><div class="card"><h3>Security</h3><p class="muted">The connected secret key is stored locally only when you choose to remember it.</p><button id="settingsLogout" class="danger" type="button">Disconnect</button></div></div>'}
function bind(p){document.querySelectorAll("[data-go]").forEach(b=>b.addEventListener("click",()=>show(b.dataset.go)));if(p==="models")document.querySelectorAll(".use-model").forEach(b=>b.addEventListener("click",()=>{show("playground");setTimeout(()=>{$("#playModel").value=b.dataset.model},0)}));if(p==="playground")$("#playRun").addEventListener("click",runPlayground);if(p==="apiKeys"){$("#copyKey").addEventListener("click",()=>navigator.clipboard?.writeText(key));$("#forgetKey").addEventListener("click",logoutDeveloper)}if(p==="projects"){$("#newProject").addEventListener("click",createProjectUI);$("#reloadProjects").addEventListener("click",loadProjects);loadProjects()}if(p==="usage")loadUsage();if(p==="builder"){$("#planBtn").addEventListener("click",planBuilder);$("#buildBtn").addEventListener("click",buildBuilder)}if(p==="billing"){loadPlans();loadOrders()}if(p==="settings")$("#settingsLogout").addEventListener("click",logoutDeveloper)}
async function runPlayground(){const kind=$("#playModel").value,input=$("#playInput").value.trim();if(!input)return;$("#playOutput").textContent="Running…";try{let d;if(kind==="image")d=await api("/v1/image",{method:"POST",body:JSON.stringify({prompt:input,quality:"medium"})});else d=await api("/v1/"+kind,{method:"POST",body:JSON.stringify({input})});$("#playOutput").textContent=d.output||d.text||d.response||JSON.stringify(d,null,2);await refreshMe()}catch(e){$("#playOutput").textContent="Error: "+e.message}}
async function planBuilder(){const p=$("#builderPrompt").value.trim();if(!p)return;$("#builderStatus").textContent="Planning…";try{const d=await api("/v1/builder/plan",{method:"POST",body:JSON.stringify({prompt:p})});lastBuilderPlan=d.plan||null;$("#planOutput").classList.remove("hidden");$("#planOutput").textContent=JSON.stringify(d.plan,null,2);await refreshMe()}catch(e){$("#planOutput").classList.remove("hidden");$("#planOutput").textContent="Error: "+e.message}finally{$("#builderStatus").textContent=""}}
async function buildBuilder(){const p=$("#builderPrompt").value.trim();if(!p)return;$("#builderStatus").textContent="Generating, reviewing, building and deploying…";try{const d=await api("/v1/builder",{method:"POST",body:JSON.stringify({prompt:p,projectName:$("#projectName").value.trim(),plan:lastBuilderPlan})});const site=d.deployment?.url?API+d.deployment.url:"";$("#buildOutput").innerHTML='<div class="notice"><strong>'+esc(d.summary||"Project generated")+'</strong><br>Build: '+esc(d.build?.status||"—")+' · Files: '+esc(d.files?.length||0)+' · Review: '+(d.review?.passed?"passed":"failed")+'<br><a class="link" href="'+esc(site)+'" target="_blank">Open deployed site →</a></div>';await refreshMe();loadProjects()}catch(e){$("#buildOutput").textContent="Error: "+e.message}finally{$("#builderStatus").textContent=""}}
async function loadProjects(){try{const d=await api("/v1/projects");$("#projectList").innerHTML=d.projects?.length?d.projects.map(p=>'<div class="project"><div><strong>'+esc(p.name)+'</strong><div class="muted small">'+esc(p.description||"No description")+'</div></div><div class="toolbar"><button class="ghost open-project" data-id="'+esc(p.id)+'" type="button">Open</button><button class="danger delete-project" data-id="'+esc(p.id)+'" type="button">Delete</button></div></div>').join(""):"<p class='muted'>No projects yet.</p>";document.querySelectorAll(".open-project").forEach(b=>b.addEventListener("click",()=>openProject(b.dataset.id)));document.querySelectorAll(".delete-project").forEach(b=>b.addEventListener("click",()=>deleteProject(b.dataset.id)))}catch(e){$("#projectList").textContent="Error: "+e.message}}
async function createProjectUI(){const name=$("#newProjectName").value.trim();if(!name)return;try{await api("/v1/projects",{method:"POST",body:JSON.stringify({name})});$("#newProjectName").value="";loadProjects()}catch(e){alert(e.message)}}
async function deleteProject(id){if(!confirm("Delete this project?"))return;try{await api("/v1/projects/"+encodeURIComponent(id),{method:"DELETE"});$("#projectWorkspace").classList.add("hidden");loadProjects()}catch(e){alert(e.message)}}
async function openProject(id){try{const d=await api("/v1/projects/"+encodeURIComponent(id));currentProject=d.project;const f=await api("/v1/projects/"+encodeURIComponent(id)+"/files");currentFiles=f.files||[];renderProjectWorkspace()}catch(e){alert(e.message)}}
function renderProjectWorkspace(){const p=currentProject,w=$("#projectWorkspace");w.classList.remove("hidden");w.innerHTML='<div class="card stack"><div class="toolbar"><div style="margin-right:auto"><h3>'+esc(p.name)+'</h3><span class="muted small">'+esc(p.id)+'</span></div><button id="buildProject" class="ghost" type="button">Build</button><button id="deployProject" class="primary" type="button">Deploy</button></div><div class="two"><div><h4>Files</h4><div id="fileList">'+(currentFiles.length?currentFiles.map(f=>'<div class="file-row"><button class="ghost file-open" data-id="'+esc(f.id)+'" type="button">'+esc(f.path)+'</button><span class="muted small">'+f.content.length+' chars</span></div>').join(""):"<p class='muted'>No files.</p>")+'</div></div><div><h4>Editor</h4><input id="filePath" class="field" placeholder="index.html"><textarea id="fileContent" class="file-editor" placeholder="File content…"></textarea><div class="toolbar" style="margin-top:8px"><button id="saveFile" class="primary" type="button">Save</button><button id="newFile" class="ghost" type="button">New file</button></div><div id="fileStatus" class="status"></div></div></div><div id="deployOutput"></div></div>';document.querySelectorAll(".file-open").forEach(b=>b.addEventListener("click",()=>editFile(b.dataset.id)));$("#saveFile").addEventListener("click",saveFile);$("#newFile").addEventListener("click",()=>{$("#filePath").value="";$("#fileContent").value="";delete $("#saveFile").dataset.id});$("#buildProject").addEventListener("click",buildProjectUI);$("#deployProject").addEventListener("click",deployProject)}
function editFile(id){const f=currentFiles.find(x=>x.id===id);if(f){$("#filePath").value=f.path;$("#fileContent").value=f.content;$("#saveFile").dataset.id=f.id}}
async function saveFile(){const path=$("#filePath").value.trim(),content=$("#fileContent").value;if(!path)return;try{const id=$("#saveFile").dataset.id;if(id)await api("/v1/projects/"+currentProject.id+"/files/"+id,{method:"PUT",body:JSON.stringify({path,content})});else await api("/v1/projects/"+currentProject.id+"/files",{method:"POST",body:JSON.stringify({path,content})});$("#fileStatus").textContent="Saved.";openProject(currentProject.id)}catch(e){$("#fileStatus").textContent="Error: "+e.message}}
async function buildProjectUI(){try{const d=await api("/v1/builds",{method:"POST",body:JSON.stringify({projectId:currentProject.id})});$("#deployOutput").innerHTML='<div class="notice">Build '+esc(d.build.status)+' — '+esc(d.build.fileCount)+' files</div>'}catch(e){$("#deployOutput").textContent="Error: "+e.message}}
async function deployProject(){try{const d=await api("/v1/hosting/deployments",{method:"POST",body:JSON.stringify({projectId:currentProject.id})});const url=API+d.deployment.url;$("#deployOutput").innerHTML='<div class="notice">Deployment: '+esc(d.deployment.status)+' — <a class="link" target="_blank" href="'+esc(url)+'">Open site</a></div>'}catch(e){$("#deployOutput").textContent="Error: "+e.message}}
async function loadUsage(){try{const d=await api("/v1/usage");$("#usageBalance").textContent=me?.credits??"—";$("#usageRequests").textContent=d.pagination?.total??d.usage?.length??0;$("#usageRecords").textContent=d.usage?.length??0;$("#usageList").innerHTML=d.usage?.length?d.usage.map(x=>'<div class="order-row"><span><strong>'+esc(x.endpoint||"service")+'</strong><br><span class="muted small">'+esc(x.createdAt||x.timestamp||"")+'</span></span><span class="pill">'+esc(x.credits_used??0)+' credits</span></div>').join(""):"<p class='muted'>No usage records.</p>"}catch(e){$("#usageList").textContent="Error: "+e.message}}
async function loadPlans(){try{const d=await api("/v1/billing/plans");$("#plans").innerHTML=d.plans.map(p=>'<div class="card plan"><h3>'+esc(p.name)+'</h3><div class="price">'+esc(p.prices?.MGA??0)+' Ar</div><div class="muted">'+esc(p.credits)+' credits / month</div><ul>'+p.features.map(f=>"<li>"+esc(f)+"</li>").join("")+'</ul>'+(p.id==="free"?"":'<button class="primary buy" data-plan="'+esc(p.id)+'" type="button">Choose plan</button>')+'</div>').join("");document.querySelectorAll(".buy").forEach(b=>b.addEventListener("click",()=>startOrder(b.dataset.plan)))}catch(e){$("#plans").textContent="Error: "+e.message}}
async function loadOrders(){try{const d=await api("/v1/billing/orders");$("#orders").innerHTML=d.orders?.length?d.orders.map(o=>'<div class="order-row"><span><strong>'+esc(o.planId||o.plan_id)+'</strong><br><span class="muted small">'+esc(o.currency)+' '+esc(o.amount)+' — '+esc(o.status)+'</span></span><span class="small">'+esc(o.id)+'</span></div>').join(""):"<p class='muted'>No orders.</p>"}catch(e){$("#orders").textContent="Error: "+e.message}}
async function startOrder(planId){try{const o=await api("/v1/billing/orders",{method:"POST",body:JSON.stringify({planId,currency:"MGA"})});const c=await api("/v1/billing/orders/"+o.order.id+"/checkout",{method:"POST",body:JSON.stringify({provider:"papi"})});if(c.checkout?.paymentLink)location.href=c.checkout.paymentLink;else alert("Checkout created but no payment link was returned.")}catch(e){alert(e.message)}}
function initFrontend(){const create=$("#createKeyBtn"),copy=$("#copyCreatedKey"),cont=$("#continueConsoleBtn"),logout=$("#logoutBtn"),mobile=$("#mobileNav");if(create)create.addEventListener("click",createDeveloperKey);if(copy)copy.addEventListener("click",copyCreatedKey);if(cont)cont.addEventListener("click",continueToConsole);if(logout)logout.addEventListener("click",logoutDeveloper);$("#developerName")?.addEventListener("keydown",e=>{if(e.key==="Enter")createDeveloperKey()});if(mobile)mobile.addEventListener("click",()=>$("#sidebar").classList.toggle("open"));document.querySelectorAll(".nav").forEach(n=>n.addEventListener("click",()=>show(n.dataset.page)));document.querySelector(".brand")?.addEventListener("click",e=>{e.preventDefault();show("overview")});if(key)showConsole();else showOnboarding()}
window.addEventListener("error",e=>{const el=$("#connectError");if(el&&$("#connectScreen")&&!$("#connectScreen").classList.contains("hidden")){el.textContent="JavaScript error: "+(e.message||"Unknown error");el.classList.remove("hidden")}});document.addEventListener("DOMContentLoaded",initFrontend);